---
version: '3'

services:
  ccd-case-document-am-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/ccd-case-document-am-api
    container_name: ccd-case-document-am-api
    environment:
      CASE_DOCUMENT_S2S_AUTHORISED_SERVICES: ccd-case-document-am-api,ccd_gw,xui_webapp
      REFORM_SERVICE_NAME: ccd-case-document-am-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      S2S_SECRET:
      IDAM_USER_URL:
      IDAM_S2S_URL:
      CCD_DOCUMENT_API_IDAM_KEY:
      USER_PROFILE_HOST:
      AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY:
      #JAVA_TOOL_OPTIONS: -XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 4455:4455
      #- 5005:5005
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
