java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:
  keyVaults:
    ccd:
      resourceGroup: ccd-shared
      secrets:

  environment:
    DEFINITION_STORE_HOST: http://ccd-definition-store-api-aat.service.core-compute-aat.internal/
