java:
  image: 'hmctspublic.azurecr.io/ccd/case-document-am-api:latest'
  applicationPort: 4455
  ingressHost: ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ccd
  environment:

